ARG NWN_VERSION=dev
FROM urothis/nwnee-community-images:ci-base-${NWN_VERSION}
LABEL maintainer "urothis@gmail.com"
ENV PATH="/home/nasher/.nimble/bin:$PATH"
RUN git clone https://github.com/squattingmonk/nasher.git && cd nasher && \
  nimble install -y && \
  chmod +x /home/nasher/.nimble/bin/nasher
ENTRYPOINT [ "nasher", "--help" ]
