FROM debian:buster AS build
WORKDIR /build
RUN apt update && apt install git cmake bison build-essential -y && git clone https://github.com/nwneetools/nwnsc.git
WORKDIR /build/nwnsc
RUN cmake . && make all
ARG NWN_VERSION=dev
FROM debian:buster
COPY --from=build /build/nwnsc/nwnsc /usr/local/bin/
ENTRYPOINT ["nwnsc", "-on", "${NWN_ROOT}"]
CMD ["*.nss"]
