name: Manual Push ARM64 Docker Images
on:
  workflow_dispatch:

jobs:
  trigger-manual-arm-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian:buster-slim", "debian:bullseye-slim", "ubuntu:focal", "ubuntu:impish"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Build and push debian nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          platforms: linux/arm64
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwserve-8193.34-${{ steps.fix-version.outputs.value }}-arm64
          cache-to: type=inline
          context: src/nwserver/assets/arm64/
          build-args: |
            IMAGE=${{ matrix.distro }}
          tags: |
            urothis/nwnee-community-images:nwserver-8193.34-${{ steps.fix-version.outputs.value }}-arm64
