name: Manual Push Docker Images
on:
  workflow_dispatch:
    inputs:
      nwn_version:
        description: 'nwn version to build images for'
        required: true

jobs:
  trigger-manual-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          repo: nwnee-community-images
          owner: urothis
          event_type: nwn_version_push
          message: |
            {
              "nwn_version": "${{ github.event.inputs.nwn_version }}"
            }
