name: Build & Push BaseNim Image

on:
  workflow_dispatch:
    inputs:
      nwnVersion:
        description: 'nwn version to produce nimbase images for.'
        required: true

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build and push nwdata-nim-${{ github.event.inputs.nwnVersion }} image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          pull: true
          file: Dockerfile.BaseNim
          build-args: |
            NWN_VERSION=${{ github.event.inputs.nwnVersion }}
          tags: |
            ${{ github.repository_owner }}/${{ github.repository }}:nwdata-nim-${{ github.event.inputs.nwnVersion }}
            ghcr.io/${{ github.repository }}:nwdata-nim-${{ github.event.inputs.nwnVersion }}
