name: Build & Push Nwserver Images

on:
  workflow_dispatch:
    inputs:
      nwnVersion:
        description: 'nwn version to produce nwserver images for.'
        required: true

jobs:
  build-push-images:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: Dockerfile.Nwserver
          build-args: |
            NWN_VERSION=${{ github.event.inputs.nwnVersion }}
            IMAGE=debian:buster-slim
          tags: |
            ${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-debian-buster
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-debian-buster
      - 
        name: Build and push debian bullseye nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: Dockerfile.Nwserver
          build-args: |
            NWN_VERSION=${{ github.event.inputs.nwnVersion }}
            IMAGE=debian:bullseye-slim
          tags: |
            ${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-debian-bullseye
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-debian-bullseye
      - 
        name: Build and push ubuntu focal nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: Dockerfile.Nwserver
          build-args: |
            NWN_VERSION=${{ github.event.inputs.nwnVersion }}
            IMAGE=ubuntu:focal
          tags: |
            ${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-ubuntu-focal
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:nwserver-${{ github.event.inputs.nwnVersion }}-ubuntu-focal
