name: Handle NWN Version based images

on:
  repository_dispatch:
    types: [nwn_version_push]

jobs:
  nwserver-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian:buster", "debian:buster-slim", "debian:bullseye", "debian:bullseye-slim", "ubuntu:focal"]
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          file: Docker/Dockerfile.nwserver
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ matrix.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ matrix.nwn_version }}-latest
            urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ matrix.nwn_version }}-${{ steps.date.outputs.date }}