name: Handle NWN Version based images

on:
  repository_dispatch:
    types: [nwn_version_push]

jobs:
  nwserver-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian:buster-slim", "debian:bullseye-slim", "ubuntu:focal", "ubuntu:impish"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Build and push debian nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: src/nwserver/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ matrix.distro }}
          tags: |
            urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}

  nwnxee-debian-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["debian:buster-slim", "debian:bullseye-slim"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Shorten distro
        id: shorten-distro
        run: |
          echo "::set-output name=value::$(echo "${{ matrix.distro }}" | cut -f1,1 -d'-')"
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ steps.shorten-distro.outputs.value }}
            find: ':'
            replace: '-'
      -
        name: Get NWNX Commit hash
        id: nwnxee_commit
        run: |
          wget https://github.com/nwnxee/unified/releases/download/build${{ github.event.client_payload.message.nwn_version }}-HEAD/NWNX-EE.zip -P /tmp/nwnx/ &&
          unzip /tmp/nwnx/NWNX-EE.zip -d . &&
          echo "::set-output name=value::$(find -iname "*.txt" -exec sh -c 'for f do basename -- "$f" .txt;done' sh {} +)"
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-image-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee${{ github.event.client_payload.message.version_fix }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: src/nwnxee/Dockerfile.debian
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-image-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{steps.nwnxee_commit.outputs.value}}

  nwnxee-debian-slim-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["debian:buster-slim", "debian:bullseye-slim"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Get NWNX Commit hash
        id: nwnxee_commit
        run: |
          wget https://github.com/nwnxee/unified/releases/download/build${{ github.event.client_payload.message.nwn_version }}-HEAD/NWNX-EE.zip -P /tmp/nwnx/ &&
          unzip /tmp/nwnx/NWNX-EE.zip -d . &&
          echo "::set-output name=value::$(find -iname "*.txt" -exec sh -c 'for f do basename -- "$f" .txt;done' sh {} +)"
      -
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee-slim-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: src/nwnxee/Dockerfile.debian.slim
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-slim-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-slim-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{steps.nwnxee_commit.outputs.value}}

  nwnxee-ubuntu-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["ubuntu:focal","ubuntu:impish"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Get NWNX Commit hash
        id: nwnxee_commit
        run: |
          wget https://github.com/nwnxee/unified/releases/download/build${{ github.event.client_payload.message.nwn_version }}-HEAD/NWNX-EE.zip -P /tmp/nwnx/ &&
          unzip /tmp/nwnx/NWNX-EE.zip -d . &&
          echo "::set-output name=value::$(find -iname "*.txt" -exec sh -c 'for f do basename -- "$f" .txt;done' sh {} +)"
      -
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: src/nwnxee/Dockerfile.ubuntu
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{steps.nwnxee_commit.outputs.value}}

  nwnxee-ubuntu-slim-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["ubuntu:focal","ubuntu:impish"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'
      -
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee-slim-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: src/nwnxee/Dockerfile.ubuntu.slim
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-slim-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{steps.nwnxee_commit.outputs.value}}

  nwnsc-build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnsc-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/nwnsc/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwnsc-${{ github.event.client_payload.message.nwn_version }}

  nwn-ci-base-build:
    needs: nwnsc-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:ci-base-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:ci-base-${{ github.event.client_payload.message.nwn_version }}

  nasher-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nasher-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/nasher/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nasher-${{ github.event.client_payload.message.nwn_version }}

  nwsync-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwsync-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/nwsync/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwsync-${{ github.event.client_payload.message.nwn_version }}

  nwnt-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnt-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/nwnt/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwnt-${{ github.event.client_payload.message.nwn_version }}

  nwsync_originate-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwsync-originate-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/nwsync_originate/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwsync-originate-${{ github.event.client_payload.message.nwn_version }}

  tlkify-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:tlkify-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: src/tlkify/Dockerfile
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:tlkify-${{ github.event.client_payload.message.nwn_version }}



