name: Handle NWN Version based images

on:
  repository_dispatch:
    types: [nwn_version_push]

jobs:
  nwserver-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["debian:buster", "debian:buster-slim", "debian:bullseye", "debian:bullseye-slim", "ubuntu:focal"]
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        uses: mad9000/actions-find-and-replace-string@2
        id: fix-version
        with:
            source: ${{ matrix.distro }}
            find: ':'
            replace: '-'   
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwserver
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ matrix.distro }}
          tags: |
            urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwserver-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{ steps.date.outputs.date }}

  nwnxee-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["debian:buster", "debian:buster-slim", "debian:bullseye", "debian:bullseye-slim", "ubuntu:focal"]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwnxee
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{ steps.date.outputs.date }}

  nwnxee-slim-build:
    needs: nwserver-build
    strategy:
      matrix:
        distro: ["debian:buster", "debian:buster-slim", "debian:bullseye", "debian:bullseye-slim", "ubuntu:focal"]
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwnxee image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnxee${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwnxee-slim
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
            IMAGE=${{ steps.fix-version.outputs.value }}
          tags: |
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}
            urothis/nwnee-community-images:nwnxee-${{ github.event.client_payload.message.nwn_version }}-${{ steps.fix-version.outputs.value }}-${{ steps.date.outputs.date }}


  nwnsc-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnsc-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwnsc
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwnsc-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:nwnsc-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}


  nwn-ci-base-build:
    needs: nwnsc-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:ci-base-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.ci-base
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:ci-base-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:ci-base-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}

  nasher-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true
          cache-from: type=registry,ref=urothis/nwnee-community-images:nasher-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.nasher
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nasher-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:nasher-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}

  nwsync-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true          
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwsync-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwsync
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwsync-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:nwsync-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}

  nwnt-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true          
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwnt-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwnt
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwnt-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:nwnt-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}

  nwsync_originate-build:
    needs: nwn-ci-base-build
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to Dockerhub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and push debian buster nwserver image
        uses: docker/build-push-action@v2
        with:
          push: true
          pull: true          
          cache-from: type=registry,ref=urothis/nwnee-community-images:nwsync-originate-${{ github.event.client_payload.message.nwn_version }}
          cache-to: type=inline
          file: Docker/Dockerfile.nwsync_originate
          build-args: |
            NWN_VERSION=${{ github.event.client_payload.message.nwn_version }}
          tags: |
            urothis/nwnee-community-images:nwsync-originate-${{ github.event.client_payload.message.nwn_version }}
            urothis/nwnee-community-images:nwsync-originate-${{ github.event.client_payload.message.nwn_version }}-${{ steps.date.outputs.date }}
